defaults: &defaults
  site_name:'Robodou'
  email_username: 'robodou@robodou.cn'
  email_form: 'DouMu<robodou@robodou.cn>'

development:
  <<: *defaults
  domain: 'http://localhost:3000'

test:
  <<: *defaults

production:
  <<: *defaults
  domain: 'http://robodou.cn'
