defaults: &defaults

  email_username: 'robodou@robodou.cn'
  email_password: 'rbd123qwe'
  email_form: 'DouMu<robodou@robodou.cn>'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults